apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bvvuiosf4-nodejs 
  janus-idp.io/tekton: bvvuiosf4-nodejs
  backstage.io/kubernetes-id: bvvuiosf4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bvvuiosf4-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml