apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bvvuiosf4-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bvvuiosf4-nodejs 
  name: bvvuiosf4-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bvvuiosf4-nodejs 
